### ISSUE TITLE
 reboot loop after setting up wlan

### ISSUE THREAD

**Issue by ovl666** [zwiebert/tronferno-mcu-bin#1]
Hello,
flashing  ESP12F, and ESP07S works ok (dio mode).
First boot and list of config also.
But after setting up WLAN with config .. and reboot, ESP stucks in a reboot loop with this messages:

(unreadable characters)
 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 29988, room 16 

(unreadable characters)

**Comment by zwiebert** [comment]
Hello, thanks for reporting. 

The options were not fully implemented. Have forgotten it.  Should now work. 

Test:

config wlan-ssid=1234567 wlan-password=abcdefg;  // no "quotes"
reply: ok
...
(after pressing reset button:)
...
main program starting ...
build-date: Nov  6 2017 18:38:48
C.fer_centralUnitID: 0x08012345
C.mcu_serialBaud: 115200
C.geo_longitude: -12.34566
C.geo_latitude: 54.32109
C.geo_timezone: 1.0
C.wifi_SSID: "1234567"
C.wifi_password: "***********"
