### ISSUE TITLE
Kann einen Sonnensensor nicht anlernen - und Kleinigkeiten. :-)

### ISSUE THREAD

**Issue by jochenpa** [zwiebert/tronferno-mcu-bin#2]
Hallo Bert

Mir gelingt es nicht, einen Sonnensensor an die MCU anzulernen. (Nach der Neuflash-Orgie, davor ging es ja.)
Obwohl ich den jetzt abgenapft und recht nahe zur MCU getragen habe wird er nicht angelernt.
Die anderen beiden Sonnensensoren und die beiden Fernbedienungen machten keine Probleme, nur dieser eine Sonnensensor ... als ob da noch was gespeichert ist aber nicht angezeigt wird ...

Es wird auch gar nichts im Log-Reiter angezeigt, obwohl ich per Test-Button auf dem Sonnensensor erfolgreich den Rolladen zum zucken bewegen kann.
Wird das im Log irgendwie gefiltert? Wäre schön wenn man da ALLES was empfangen wird angezeigt bekommt, unabhängig davon ob es angelernt ist oder nicht, gerne auch die Sachen vom Nachbarn (bei mir hat keiner das gleiche System in der Nähe, aber falls ...)
Und es wäre auch schön, wenn XX Zeilen gespeichert werden, damit man das auch dann im Log sieht, wenn man es nicht offen hatte ...

(Aktuelle Beta 0.11.2.5 ist installiert.)

Dann noch eine Kleinigkeit, der Reiter "Auto" wird auf dem iPhone unvollständig dargestellt, man kann nicht komplett nach links scrollen, um alles anzuzeigen. Nach rechts geht das schon ... links ist es abgeschnitten.
(Quer gehalten geht es, also keine wichtige Sache, aber vermutlich auch keine schwierige Sache.)

Noch so eine Kompatibilitäts-Sache:
Auf dem iPhone macht der Reiter "Alias" Probleme.
Man kann ihn zwar benutzen, aber das Feld "All" und "This G/E" wird nicht richtig dargestellt.

Dann eine UI-Geschichte:
Kann man irgendwie besser anzeigen, ob "Start Pairing" gedrückt würde?
Vielleicht so wie beim Speichern bei "Auto", wo es dann einen Countdown gibt?
Wie lange bleibt denn "Start Pairing" aktiv nach dem drücken?
Wenn es mehr als ein paar Sekunden sind vielleicht eine kurze Text-Einblendung "aktiv für xx Minuten" oder so?

Mit freundlichen Grüßen Jochen

**Comment by zwiebert** [comment]
Hallo Jochen,

danke für den Report. Ich bin gerade beim Testen des Sonnensensors. Ist hier auch genau so.  Hatte da irgendwie die Hardware in Verdacht, dass der Empfänger zu schlecht empfängt, aber müsste dann ja doch eher ein Softwareproblem sein.  Werde mir das Problem als erstes vornehmen.

**edit**: also gefiltert werden nur events mit unbekannten Kommandos. Die erscheinen dann wohl nur im Terminal als rohe Hex-Zahlen. Der Test-Knopf des Sonnensensors war so ein unbekanntes Kommando.  Der "SO POS INST" Knopf erzeugt aber eigentlich einen Logeintrag ("sun-pos"), wenn er denn empfangen wird.  Bin mir noch nicht sicher warum das Pairing nicht klappt.  Ob nicht doch nur das Sende-Signal zu schwach ist.

Beim Chrome muss ich manchmal im Browsermenu ein Häkchen bei  "Desktopwebseite" machen, wenn der Tab zu breit ist.  Sollte aber in der Release-Version natürlich nicht nötig sein. Werde mir das gelegentlich alles anschauen.

Das mit dem Pariring war auch eher provisorisch zusammengebastelt. Werde mich dem auch mal annehmen. Könnte aber alles etwas dauern.  Sollte es lieber langsam aber dafür gleich richtig machen und nicht wieder ein Provisorium.

mfG und schönes Wochenende,
Bert

**Comment by jochenpa** [comment]
Hallo Bert

Ich habe es gerade mit der 0.11.2.6 probiert, jetzt konnte ich den 3. Sonnensensor direkt anlernen.
Auch der Test-Knopf wird jetzt erkannt, danke schön. :-)


Mit freundlichen Grüßen Jochen
