### ISSUE TITLE
Wunschliste: Zeitsynchronisation

### ISSUE THREAD

**Issue by jochenpa** [zwiebert/tronferno-mcu-bin#3]
Hallo Bert

Ich wünsche mir einen Tab, auf dem ich für jeden Motor einzeln einstellen kann, wann er wöchentlich oder monatlich die Zeit übertragen bekommt. Also auch die Uhrzeit muss auswählbar sein, da jeder vermutlich eigene Vorstellungen davon hat wann es OK ist, dass der Motor rappelt.
(Ich würde es denke ich eine Minute nach der Schließ-Zeit einstellen.)
Monatlich würde vermutlich reichen, wöchentlich wäre aber auch OK, täglich wäre denke ich zu viel.

Und hast Du Dir schon Gedanken um die Zeitumstellung gemacht?

Mit freundlichen Grüßen Jochen

**Comment by zwiebert** [comment]
Hallo Jochen,

die Uhren laufen synchron mit der Netzfrequenz. Das heißt, wen man die Zeit einmal an alle Motore gleichzeitig geschickt hat, dann werden die Uhren bis in alle Ewigkeit gleich laufen.  Beim Programmieren eines Timers wird aber immer die Uhrzeit mitgesendet und aktualisiert. Deshalb gerät dann ein Motor aus dem Tritt.

Der einzig sichere Zeitpunkt zum stellen wäre *vor* einer vorgeinstellten Timer-Zeit.  Dann wäre garantiert, dass der Timer wirklich ausgeführt wird, egal wie falsch die Uhr vorher gestellt war.  Und die Astro-Zeiten würden auch wegfallen, weil nicht sicher ist, welche Zeiten-Tabelle der Motor dafür gespeichert hat und selbst wenn, dann manchmal die Zeit von Tronferno nicht richtig vorhergesagt wird (also welcher Tabelleneintrag für welchen Tag gilt).

Es wäre viel einfacher zu programmieren nur einen Zeitpunkt zur Zeitsynchronisation für alle Rolläden festzulegen.  Damit wär das Problem verhindert, dass die Uhren der Motoren untereinander abweichen und die Bedienung des Features wäre nicht so kompliziert.  Das mit der Zeitumstellung würde ich dann da mit integrieren.

Bin zur Zeit doch eher auf dem Trip das Einfache (beim programmieren und bei der Bedienung) möglichst zu bevorzugen auch wenn das dann nicht perfekt ist.  Für weitergehendes kann man immer noch mit einem Skript alle Kommandos die man nur möchte an Tronferno senden, also auch das Zeit senden.

mfG,
Bert

**Comment by jochenpa** [comment]
Hallo

Bei mir laufen die nicht Netzsynchron, sondern driften so ca. eine halbe Sekunde pro Tag auseinander (bei einigen Empfängern, bei anderen ist es nicht ganz so viel, man merkt es erst nach ein paar Wochen.).
Wo hast Du diese Info mit der Netzsynchronität her? Steht das irgendwo im Datenblatt?

Wenn es zu aufwändig ist wäre auch eine Uhrzeit für die Zeitübertragung an alle Empfänger OK.

Wie wäre es mit einem Knopf dafür?

Warum ist es eigentlich so, dass die MCU erst ein paar Sekunden nach der programmierten Zeit beginnt sich gemäß der Timer-Programmierung auf oder ab zu bewegen? Das Teil sollte doch per NTP eine exakte Zeit haben ...

Mit freundlichen Grüßen Jochen

**Comment by zwiebert** [comment]
Guten Abend Jochen,

...das mit dem netzsynchron ist dann wohl ein Irrtum meinerseits.   Kam mir immer so vor, als würden die Uhren manchmal ziemlich falsch gehen, aber trotzdem die Rollläden gleichzeitig runtergehen.  Aber da kann ich mich auch getäuscht haben. 

Die Zeitübertragunng an alle Empfänger ging etwas indirekt, indem man in der Liste "A" ausgewählt hat.  Hab das zufällig aber gerade sowieso geändert.  Da mich der Button dort unten neben Speichern verwirrt hat und am neuen Ort noch Platz für einen zweiten Button war.  Das Einbauen der automatische Zeiteinstellen folgt dann später, aber vermutlich nicht mehr rechtzeitig zur Zeitumstellung.

Bin mir nicht sicher warum die Bewegung zu spät angezeigt wird (war das nicht eher exakt eine Minute?). Der ganze Code dafür ist aber abartig kompliziert und und umfangreich, dass ich da schon lange nicht mehr aus dem Kopf weiß.  Er checkt wohl jede Minute ob irgendein Timer-Event jetzt fällig ist in dieser Minute.  Dann wird der Event aus der Liste entfernt und die Bewegung ausgelöst. Das passiert wenn die Minute abgelaufen ist um zu verhindern, dass der Event gleich wieder neu in die Liste aufgenommen wird.  Hatte irgendwas mit dem Tageswechsel und den Wochentagstimern zu tun, warum es nicht vernünftig ging wenn die Minute anfängt. War vielleicht auch nur ein Provisorium... 

MfG, Bert

**Comment by jochenpa** [comment]
Hallo Bert

Der Knopf ist schon mal prima, danke.

Ich habe noch mal genauer geschaut, die MCU zeigt die Timer-Bewegung ca. 50 Sekunden nach dem programmierten Zeitpunkt an.


Mit freundlichen Grüßen Jochen

**Comment by jochenpa** [comment]
Hallo Bert

Heute habe ich noch mal geschaut, es könnte wirklich genau 1 Minute später sein.
Das wäre auch eher logisch, aber sicher auch einfacher zu beheben ... :-)

Mit freundlichen Grüßen Jochen

**Comment by zwiebert** [comment]
Hallo Jochen,

bin mir nicht sicher.  Da ich ja inzwischen von C auf C++ gewechselt bin lässt sich das Problem vielleicht jetzt einfacher lösen. Ist nun doch alles viel übersichtlicher geworden.  Werde mir das mal anschauen wen ich Zeit habe.

MfG, Bert

**Comment by zwiebert** [comment]
Hallo Jochen,

seit Version 0.11.2.26 sollte die Timer-Bewegung nun zum programmierten Zeitpunkt starten.  Das mit der automatischen Zeitsynchronisation ist noch zu erledigen.

MfG, Bert

**Comment by jochenpa** [comment]
Hallo Bert

Gibt es hier schon etwas neues?
Oder als Lösung gibt es eine Möglichkeit per fhem einen Zeit-Synchronisier-Befehl abzusetzen?
Ich denke der Befehl wäre dann "timer rtc-only", aber ich verstehe noch nicht wie ich
1. den Befehl an einen bestimmten Actuator sende und
2. den Befehl von fhem aus senden kann.
Geht das überhaupt so?


Mit freundlichen Grüßen
Jochen

**Comment by zwiebert** [comment]
Hallo Jochen,

ist ja bald wieder Zeitumstellung.  Hab da bisher noch nichts in der Firmware dafür gemacht. :(

Dem FHEM Modul scheint wohl das passend SET zum Senden von Zeit/Datum zu fehlen. Werde ich in Kürze dort ergänzen, dann kann man das erstmal mit einem "at" aus FHEM heraus automatisch synchronisieren.


1. Gerät für "Alle Rollläden" anlegen, falls noch nicht vorhanden.
```

defmod roll00 Tronferno g=0
attr roll00 IODev tfmcu
attr roll00 alexaName Haus Rollo
attr roll00 genericDeviceType blind
attr roll00 room Shutter,Tronferno
attr roll00 webCmd up:stop:down:sun-down:pct


```

2. Dann darüber den neuen Befehl "rtc-sync" (?) an alle Rollläden senden

`set roll00  rtc-sync
`

Aber muss ich erst noch einbauen...  sage ich dann hier nochmal Bescheid.

mfg Bert

**Comment by jochenpa** [comment]
Hallo Bert

Ich habe einen Rolladen der etwas speziell zu behandeln ist.
Das kleine bisschen ruckeln als Antwort auf den Zeit-Befehl würde bei dem ausreichen dass er ein
Stück hinunter fährt und damit die Fliegen-Blende blockiert.
Somit möchte ich nicht die Zeit an alle Rolladen senden sondern einzeln.
Ich denke per fhem kann man das sicher automatisieren, den Teil suche ich mir dann schon zusammen.
Aber ich bräuchte dann ein Beispiel wie ich nur für einen Aktuator die Zeit senden kann ...

Danke schon mal im Voraus :-)


Mit freundlichen Grüßen
Jochen

**Comment by zwiebert** [comment]
Hallo Jochen, du könntest die Zeit zweimal senden.  Dann würden sie gleich wieder hochfahren. Aber du kannst natürlich auch den Befehl an nur einzelne Empfänger oder Gruppen senden. Habs nur kurz getestet und sollte ungefähr so gehen:

```

defmod roll00 Tronferno g=0
...
defmod roll10 Tronferno g=1
...
defmod roll11 Tronferno g=1 m=1
...

```

An eizelnen Empfänger senden

`set roll11 rtc-sync
`

An alle Empfänger der Gruppen 1 und 3 senden und an Empfänger 2 und 3 von Gruppe 2 (aber nicht Empfänger 1):

`{ fhem("set roll10 rtc-sync;;set roll22 rtc-sync;;set roll23 rtc-sync;;set roll30 rtc-sync") }

oder direkt

set roll10 rtc-sync;;set roll22 rtc-sync;;set roll23 rtc-sync;;set roll30 rtc-sync

als at Gerät (täglich 17 Uhr):

define a4 at *17:00:00 set roll10 rtc-sync;;set roll22 rtc-sync;;set roll23 rtc-sync;;set roll30 rtc-sync

`



mfg Bert

**Comment by zwiebert** [comment]
...hab das Modul mit der neuen Option hochgeladen. Update (hoffentlich) wie immer mit:

` update all https://raw.githubusercontent.com/zwiebert/tronferno-fhem/master/modules/tronferno/controls_tronferno.txt`

**Comment by jochenpa** [comment]
Hallo Bert

Das scheint gut zu funktionieren, vielen Dank.
Damit ist dieses "Problem" für mich erledigt.


Mit freundlichen Grüßen
Jochen

**Comment by jochenpa** [comment]
Hallo Bert

Ich glaube es gibt noch ein kleines Timing-Problem mit der Funktion.
Wenn mehrere rtc-sync-Befehle in einem Rutsch angegeben werden (mit ; getrennt) werden einige davon verschluckt.
(Bevorzugt der erste wie es scheint.)
Ich kann das sehr gut testen mit einem Empfänger der eigentlich jeden Befehl mitbekommen müsste, da er sich in unmittelbarer Nähe zum Sender befindet.
Wenn ich dort hin nur einen sync-Befehl sende kommt er immer an.
Sende ich zwei Mal den sync-Befehl an diesen Empfänger kommt nur einer an.
Sende ich drei Befehle kommen zwei an.
Bei fünf oder mehr Befehlen wird noch mehr verschluckt ...

Im Log stehen auch unterschiedliche Sachen obwohl ich immer das gleiche sende, oder ist das Normal?:

```
2022.11.28 21:45:37 3: Rolladen_Buero:command: {"auto":{"mid":82,"g":2,"rtc-only":1,"m":3}}
2022.11.28 21:45:37 3: Rolladen_Buero:command: {"auto":{"g":2,"rtc-only":1,"mid":82,"m":3}}
2022.11.28 21:45:37 3: Rolladen_Buero:command: {"auto":{"rtc-only":1,"g":2,"mid":82,"m":3}}
2022.11.28 21:45:37 3: Rolladen_Buero:command: {"auto":{"m":3,"g":2,"rtc-only":1,"mid":82}}
2022.11.28 21:45:37 3: Rolladen_Buero:command: {"auto":{"m":3,"g":2,"rtc-only":1,"mid":82}}
2022.11.28 21:45:49 3: Rolladen_Buero:command: {"auto":{"rtc-only":1,"g":2,"mid":82,"m":3}}
2022.11.28 21:45:49 3: Rolladen_Buero:command: {"auto":{"m":3,"g":2,"rtc-only":1,"mid":82}}
2022.11.28 21:45:49 3: Rolladen_Buero:command: {"auto":{"m":3,"mid":82,"g":2,"rtc-only":1}}
2022.11.28 21:45:49 3: Rolladen_Buero:command: {"auto":{"m":3,"rtc-only":1,"g":2,"mid":82}}
2022.11.28 21:45:49 3: Rolladen_Buero:command: {"auto":{"mid":82,"rtc-only":1,"g":2,"m":3}}
2022.11.28 21:45:49 3: Rolladen_Buero:command: {"auto":{"g":2,"rtc-only":1,"mid":82,"m":3}}
2022.11.28 21:45:49 3: Rolladen_Buero:command: {"auto":{"g":2,"rtc-only":1,"mid":82,"m":3}}
2022.11.28 21:45:49 3: Rolladen_Buero:command: {"auto":{"m":3,"mid":82,"rtc-only":1,"g":2}}
2022.11.28 21:46:12 3: Rolladen_Buero:command: {"auto":{"g":2,"rtc-only":1,"mid":82,"m":3}}
2022.11.28 21:46:12 3: Rolladen_Buero:command: {"auto":{"m":3,"g":2,"rtc-only":1,"mid":82}}

```

Mit freundlichen Grüßen
Jochen

**Comment by zwiebert** [comment]
Hallo Jochen, danke für die Info.

Hab mir das gestern angeschaut und die Kommandos werden alle gesendet (laut Logikanalyzer am Sende-Pin), aber vermutlich sind entweder die Pausen dazwischen zu kurz oder die Daten selber sind beschädigt. Der Programmcode ist (noch) nicht 100%ig darauf ausgelegt, dass mehrere "auto" Kommandos direkt hintereinander gesendet werden.

...das sich die Reihenfolge in den JSON Objekten ändert ist kein Problem und vmtl. normal. Die Reihenfolge ist undefiniert und es kommt nur auf die Schlüssel-Namen an.

mfg Bert

**Comment by jochenpa** [comment]
Hallo Bert

Und wie ist der Plan? Vermutlich reicht es, an irgendeiner Stelle eine Pause zu programmieren,
beispielsweise in FHEM-Modul ... oder am Besten in der MCU?
Es darf ja auch pro Befehl gerne 2-3 Sekunden dauern, Hauptsache es klappt zuverlässig.

Interessant finde ich aber auch, dass gerade der erste von fünf Kommandos zuverlässig _nicht_ klappt.

Mit freundlichen Grüßen
Jochen

**Comment by jochenpa** [comment]
Hallo noch mal

Ich habe jetzt bei dem timer-Befehl jeweils ein "sleep 2 quiet" mit eingebaut, damit funktioniert es ...
Ist natürlich nur eine Umgehung des Problems aber immerhin ...

Mit freundlichen Grüßen
Jochen

**Comment by zwiebert** [comment]
Hallo Jochen,  ich werde das in der Firmware ändern müssen, vielleicht einen Teil neu schreiben.   Wenn das erste Kommando von fünf nicht klappt, dann ist wohl nicht die zu kurze Pause beim Senden, sondern überschriebene Daten.  Dann konzentrier ich mich erstmal darauf.

mfg Bert

**Comment by zwiebert** [comment]
...Beta-Version 0.12.1.6: Jedes "auto rtc-only" Kommando verwendet einen eigenen Speicher für die Daten. Ein Überschreiben der Daten sollte nicht mehr möglich sein. Vielleicht ist das Problem damit schon erledigt?

Im Log der Web-App erscheinen jetzt auch diese Kommandos (nur senden, kein empfangen).

mfg Bert

**Comment by jochenpa** [comment]
Hallo Bert

Sieht gut aus, danke schön.


Mit freundlichen Grüßen
Jochen
