### ISSUE TITLE
MQTT Fragen/Probleme

### ISSUE THREAD

**Issue by Frank363** [zwiebert/tronferno-mcu-bin#5]
Hallo Bert,

vielen Dank erstmal für Dein tolles Tronferno Projekt. Ich habe alles innerhalb von 2-3 Stunden
ans Laufen bekommen. Zum Einsatz kommen soll die Rollosteuerung im IOBroker und ich werde somit
MQTT einsetzen.

Jetzt sind mir 2 Sachen aufgefallen:

1. Ich finde keinen MQTT-Befehl, um alle Rollos gleichzeitig zu steuern. Per CLI oder mit dem
	FHEM_Modul geht es, aber per MQTT ist es mir nicht gelungen (tfmcu/0/pct 100 funktioniert nicht).

2. Wenn alle Rollos über die CU gesteuert werden, wird für alle Rollos von 10 bis 77 eine MQTT
	Nachricht geschickt, also 50 Messages, obwohl ich nur 5 Rollos habe und dies so im WebGui
	definiert habe.

Mache ich was falsch oder falls nicht, könntest Du das anpassen/verbessern?

Viele Grüße
Frank

**Comment by zwiebert** [comment]
Hallo Frank,

danke für das Feedback.

zu 1) ich glaube man muss /00/ verwenden für "Alle Empfänger".

zu 2) muss ich mir mal anschauen. Eigentlich sollten Positions-Daten nicht für deaktivierte Gruppen und Empfäger erzeugt werden.  Nur für die Empfänger welche auch in der WebGUI unter "%%" aufgelistet ist. Und das sollte von er Einstellung Zahnrad->MCU->Sonstige->Anzahl_Empfäger_Je_Gruppe abhängen. 

mfg, Bert

**Comment by Frank363** [comment]
Hallo Bert,

zu 1) funktioniert mit /00/ !

zu 2) Ich habe in der Konfig folgendes eingestellt:
Anzahl Empfänger je Gruppe
G1	G2	G3	G4	G5	G6	G7
1      3      1      0      0      0     0

Trotzdem werden tfmcu/11/pct_out bis tfmcu/77/pct_out gesendet, wenn ich z.b. die Rollos
mit tfmcu/00/cmd up hochfahre.

Für die Gruppen bekomme ich übrigens tfmcu/40/pct_out **101**, was auch etwas unschön ist.

Viele Grüße
Frank

**Comment by zwiebert** [comment]
Hallo Frank,

bin erst jetzt dazu gekommen. Hab das Problem schnell gefunden und gefixt. Wird also in der nächsten Beta-Version behoben sein. Danke für den Bug-Report.

mfg, Bert
